### ISSUE TITLE
Error using haussmeister in suite2p, Reading experiment settings

### ISSUE THREAD

**Issue by suhang96** [neurodroid/haussmeister#5]
Hi,

I've been using haussmeister to import RAW files into suite2p before and it is super useful. Thanks!
Recently after a re-install of the ThorImage software (both were ThorImage 4.0, 2019 vs 2020), I ran into this problem of reading the experiment settings with haussmeister.
I've attached an experiment setting example here, as well as an old experiment setting which works.
Could you help me check what could be causing this issue? 
Many thanks!
---Shuhan

[Experiment_new_has_error.txt](https://github.com/neurodroid/haussmeister/files/6792543/Experiment_new_has_error.txt)
[Experiment_old_works.txt](https://github.com/neurodroid/haussmeister/files/6792551/Experiment_old_works.txt)

Error I got:
```

 >>>>> started run at 09/07/2021 11:37:37Couldn't import libtiff

>>>ERROR<<<
cv2 module not found

cv2 unavailable

>>>ERROR<<<
pyfftw unavailable

ipyparallel unavailable

CaiMan import failed

ipyparallel unavailable

>>>ERROR<<<
stfio module missing

{'data_path': ['F:/Imaging_2p/spd/NP07C/070821/NP07C_001'], 'subfolders': [], 'save_path0': 'F:/Imaging_2p/spd/NP07C/070821/NP07C_001', 'fast_disk': 'F:/Imaging_2p/spd/NP07C/070821/NP07C_001', 'input_format': 'haus'}

Reading experiment settings for F:\Imaging_2p\spd\NP07C\070821\NP07C_001... >>>ERROR<<<
Traceback (most recent call last):

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code

>>>ERROR<<<
    exec(code, run_globals)

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>

>>>ERROR<<<
    main()

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main

    run_s2p(ops, db)

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 402, in run_s2p

    ops0 = convert_funs[ops['input_format']](ops.copy())

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 398, in <lambda>

>>>ERROR<<<
    'haus': lambda ops: haussio.load_haussio(ops['data_path'][0]).tosuite2p(ops.copy()),

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\haussmeister\haussio.py", line 1483, in load_haussio

    return ThorHaussIO(dirname, 'A')

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\haussmeister\haussio.py", line 637, in __init__

    width_idx, maxtime)

  File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\haussmeister\haussio.py", line 121, in __init__

    self._get_dimensions()

   File "c:\users\shuha\anaconda3\envs\suite2p\lib\site-packages\haussmeister\haussio.py", line 706, in _get_dimensions

    self.plane= int(child.attrib['steps'])

KeyError: 'steps'

```

Suite2p conda env:
```
# packages in environment at C:\Users\shuha\anaconda3\envs\suite2p:
#
# Name                    Version                   Build  Channel
attrs                     20.3.0                   pypi_0    pypi
bcrypt                    3.2.0                    pypi_0    pypi
blas                      1.0                         mkl
bottleneck                1.3.2                    pypi_0    pypi
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.5                   pypi_0    pypi
contours                  0.0.2                    pypi_0    pypi
cryptography              3.4.6                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                    pypi_0    pypi
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2                   pypi_0    pypi
git                       2.23.0               h6bb4b03_0
h5py                      2.10.0                   pypi_0    pypi
haussmeister              0.2.0                    pypi_0    pypi
hdmf                      1.6.4                    pypi_0    pypi
icu                       68.1                 h0e60522_0    conda-forge
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.7.0                    pypi_0    pypi
intel-openmp              2020.3             h57928b3_311    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.8.0                    10_mkl    conda-forge
libcblas                  3.8.0                    10_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_0    conda-forge
liblapack                 3.8.0                    10_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
llvmlite                  0.31.0           py37hc8dfbb8_1    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.3.4            py37h03978a9_0    conda-forge
matplotlib-base           3.3.4            py37h3379fd5_0    conda-forge
mkl                       2019.3                      203
mkl_fft                   1.0.10           py37hfa6e2cd_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
natsort                   7.1.1                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
numba                     0.48.0           py37he350917_0    conda-forge
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.18.5           py37hae9e721_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1j               h2bbff1b_0
pandas                    1.2.3                    pypi_0    pypi
paramiko                  2.7.2                    pypi_0    pypi
pillow                    8.1.1            py37h96663a1_0    conda-forge
pip                       21.0.1           py37haa95532_0
pycparser                 2.20                     pypi_0    pypi
pynacl                    1.4.0                    pypi_0    pypi
pynwb                     1.3.3                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtgraph                 0.11.1                   pypi_0    pypi
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.7.10          h7840368_100_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
qt                        5.12.9               h5909a2a_4    conda-forge
rastermap                 0.1.3                    pypi_0    pypi
ruamel-yaml               0.16.13                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
sbxreader                 0.1.5                    pypi_0    pypi
scanimage-tiff-reader     1.4.1                    pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              0.24.1           py37heb15398_0    conda-forge
scipy                     1.6.0            py37h6db1a17_0    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
shapely                   1.7.1                    pypi_0    pypi
sima                      1.3.2                    pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
suite2p                   0.9.4.dev32+g9fde007          pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tbb                       2021.1.1             h2d74725_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2021.3.5                 pypi_0    pypi
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge
```

```
(suite2p) C:\Users\shuha>conda info

     active environment : suite2p
    active env location : C:\Users\shuha\anaconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\shuha\.condarc
 populated config files : C:\Users\shuha\.condarc
          conda version : 4.9.2
    conda-build version : 3.20.4
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\shuha\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\shuha\anaconda3\pkgs
                          C:\Users\shuha\.conda\pkgs
                          C:\Users\shuha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\shuha\anaconda3\envs
                          C:\Users\shuha\.conda\envs
                          C:\Users\shuha\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by neurodroid** [comment]
Hi,

Good to hear that haussmeister is useful.

I suppose that ThorLabs changed the format of their Experiment.xml file between versions.

I’m not using ThorImage any longer. Maybe Dahlia Kushinsky or Sonja Blumenstock (cc’d) know anything about this?

Otherwise I’d recommend looking into the Experiment.xml file and see which attributes have changed between versions.

It looks like there was an attribute ’steps’ in the previous version that is not around any longer.

Best wishes
Christoph
