### ISSUE TITLE
Installing stfio and importing haussio in haussmeister for suite2p

### ISSUE THREAD

**Issue by aashishkhimasia** [neurodroid/haussmeister#6]
Hi,

Thanks for developing this tool!

I am using haussmeister for the first time to import raw files into suite2p, but I am having issues with installing and getting it up and running. 

I am unable to install the stfio module with conda after the original failed installment, and have tried to use build and install it using the setup.py file that from stimfit based on responses to this previous issue [https://github.com/neurodroid/stimfit/issues/9](url). However, I have been unable to pass this error after trying to download the boost library **C:\Users\akhim\suite2p_2\src\libstfio\abf\axon\AxAbfFio32\./../../../stfio.h(28): fatal error C1083: Cannot open include file: 'boost/function.hpp': No such file or directory**: 

![image](https://user-images.githubusercontent.com/72612451/147834469-a89063ff-711a-48ef-bdfd-35142922e5de.png)

Further, importing haussio from haussmeister in run_s2p.py fails, leading to the error. I have tried installing haussmeister and running suite2p with haus input several times in different environments. In both environments the haussmeister package is installed but importing haussio from haussmeister in run_s2p.py fails. 

In one environment, on one computer, I am stopped by this error:

`creating new log file
2021-12-31 13:54:58,007 [INFO] WRITING LOG OUTPUT TO C:\Users\akhim\.cellpose\run.log
CaiMan import failed
>>>ERROR<<<
stfio module missing
{'data_path': ['Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 freqlist3'], 'subfolders': [], 'save_path0': 'Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 freqlist3', 'fast_disk': 'Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 freqlist3', 'input_format': 'haus'}
Reading experiment settings for Z:\Leena\2P imaging Aud\NDNFdgCre_Ai162\B-111_A_1_P14\L2 freqlist3... done
Reading Z:\Leena\2P imaging Aud\NDNFdgCre_Ai162\B-111_A_1_P14\L2 freqlist3\Image_001_001.raw...
>>>ERROR<<<
Traceback (most recent call last):
>>>ERROR<<<
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 409, in run_s2p
>>>ERROR<<<
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 405, in <lambda>
>>>ERROR<<<
    'haus': lambda ops: haussio.load_haussio(ops['data_path'][0]).tosuite2p(ops.copy()),
  File "C:\Users\akhim\Anaconda3\envs\suite2p\lib\site-packages\haussmeister\haussio.py", line 370, in tosuite2p
>>>ERROR<<<
    reg_file[j].write(bytearray(im2write))
>>>ERROR<<<
OSError: [Errno 22] Invalid argument`

In another environment on a different computer, I am stopped by this error:
`reating new log file
2021-12-31 16:50:25,338 [INFO] WRITING LOG OUTPUT TO C:\Users\khimasad\.cellpose\run.log
{'data_path': ['Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 reg 1freqlist3 10'], 'subfolders': [], 'save_path0': 'Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 reg 1freqlist3 10', 'fast_disk': 'Z:/Leena/2P imaging Aud/NDNFdgCre_Ai162/B-111_A_1_P14/L2 reg 1freqlist3 10', 'input_format': 'haus'}
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\site-packages\suite2p\run_s2p.py", line 409, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\Users\khimasad\Anaconda3\envs\suite2p_2\lib\site-packages\suite2p\run_s2p.py", line 405, in <lambda>
    'haus': lambda ops: haussio.load_haussio(ops['data_path'][0]).tosuite2p(ops.copy()),
NameError: name 'haussio' is not defined
Interrupted by error (not finished)`

As aforementioned, there seems to be a problem with the haussmeister installation, despite the package being installed in the environment. 

If you have any ideas as to what may be the problem, questions or suggestions about solving this, please let me know! Thanks

**Comment by neurodroid** [comment]
Which setup.py file are you running at the very beginning of your post? To my knowledge, neither haussio nor suite2p have stfio as a dependency.

**Comment by aashishkhimasia** [comment]
I am using setup.py from haussmeister. Thanks

**Comment by neurodroid** [comment]
> I am using setup.py from haussmeister. Thanks

No, the setup.py file that you're running is not from haussmeister, it seems to be from stimfit. You do not need to install stimfit or stfio for haussmeister to run.

**Comment by aashishkhimasia** [comment]
> No, the setup.py file that you're running is not from haussmeister, it seems to be from stimfit. You do not need to install stimfit or stfio for haussmeister to run.

Ah my mistake, indeed at the beginning of the post I was using the setup.py file from stimfit. 

However, on a different machine where I have installed haussmeister (and not stimfit) in my suite2p environment, it seems that importing haussio from haussmeister in run_s2p.py fails (as is shown in the last section of the post). 

If you have any suggestions for attempting to resolve this please let me know.
